apiVersion: v1
kind: ServiceAccount
metadata:
  name: anonymous
  namespace: 24-wp
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: anonymous
  namespace: 24-wp
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create","delete","get","update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create","delete","get","update"]  
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create","delete","get","update"]   
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["create","delete","get","update"]
- apiGroups: [""]
  resources: ["persistentvolume"]
  verbs: ["create","delete","get","update"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create","delete","get","update"]    
  
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: anonymous
  namespace: 24-wp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: anonymous
subjects:
- kind: User
  name: system:anonymous
  namespace: 24-wp